apiVersion: batch/v1
kind: CronJob
metadata:
  name: callout
  namespace: default
spec:
  # schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "* * * * *" # Cron schedule (runs every 3 days at midnight)
  # schedule: "0 0 */3 * *" # Cron schedule (runs every 3 days at midnight)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: callout
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - >
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/8360 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/6196 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/5423 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/8280 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/5691 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/8753 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/8384 &&
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/7900
          restartPolicy: OnFailure
