apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: api-cronjob
  namespace: cronjob
spec:
  schedule: "0 0 */3 * *" # Cron schedule (runs every 3days at midnight)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-curl
              image: buildpack-deps:curl
              command:
                - /bin/sh
                - -c
                - |
                  curl -s -X GET https://www.meshada.com/api/pepper/find/6196 &
                  curl -s -X GET https://www.meshada.com/api/pepper/find/5423 &
                  curl -s -X GET https://www.meshada.com/api/pepper/find/8280 &
                  curl -s -X GET https://www.meshada.com/api/pepper/find/5691 &
                  curl -s -X GET https://www.meshada.com/api/pepper/find/8753
          restartPolicy: OnFailure
