apiVersion: batch/v1
kind: CronJob
metadata:
  name: callout
  namespace: default
spec:
  # schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  # schedule: "* * * * *" # Cron schedule (runs every 3 days at midnight)
  schedule: "0 0 */3 * *" # Cron schedule (runs every 3 days at midnight)
  # startingDeadlineSeconds: 86400 # 24 hours in seconds (adjust as needed)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: callout
              image: buildpack-deps:curl
              command:
                - /bin/sh
                - -c
                - >
                  curl -s -X GET http://meshada-api-service:9090/api/pepper/find/all
          restartPolicy: OnFailure
