apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjob
  namespace: default
spec:
  schedule: "0 0 */3 * *" # Cron schedule (runs every 3 days at midnight)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-curl
              image: buildpack-deps:curl
              command:
                - /bin/sh
                - -c
                - >
                  curl -s -X GET http://meshada-api-service/api/store/pepperstore  
                  curl -s -X GET http://meshada-api-service/api/pepper/find/6196 
                  curl -s -X GET http://meshada-api-service/api/pepper/find/5423 
                  curl -s -X GET http://meshada-api-service/api/pepper/find/8280 
                  curl -s -X GET http://meshada-api-service/api/pepper/find/5691 
                  curl -s -X GET http://meshada-api-service/api/pepper/find/8753
          restartPolicy: OnFailure
