apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-04-16T13:08:08Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.28.0
  name: argo-cd-argocd-server
  namespace: argocd
spec:
  # clusterIP: 10.43.87.100
  # clusterIPs:
  #   - 10.43.87.100
  # internalTrafficPolicy: Cluster
  # ipFamilies:
  #   - IPv4
  # ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8011
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8012
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  # sessionAffinity: None
  # type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: devtools-meshada-argocd-staging.meshada.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 8011
  # tls:
  #   - hosts:
  #       - devtools-meshada-argocd-staging.meshada.com
  #     secretName: argocd-secret
