apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-tools
  # annotations:
  #     prometheus.io/scrape: "true"
  #     prometheus.io/path: /
  #     prometheus.io/port: "8081"
spec:
  selector:
    app: nexus-server
  type: ClusterIP
  ports:
    - name: port-8081
      port: 8081
      targetPort: 8081
    - name: port-8082
      port: 8082
      targetPort: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: devops-tools
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: docker-staging.meshada.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8082
  tls:
    - hosts:
        - docker-staging.meshada.com
      secretName: docker-staging-secret
