apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
  count: 1
  elasticsearchRefs:
    - name: quickstart
      clusterName: qs
  version: 8.8.2
  podTemplate:
    spec:
      containers:
        - name: logstash
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 1Gi
              cpu: 1
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            cacert => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
          elastic_app_search {
            engine => "meshada-search-engine"
            api_key => "private-rriia9t7gjom9e129cgf2zpa"
            url => "http://enterprise-search-quickstart-ent-http"
          }
        }

---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.8.2
  # http:
  #   service:
  #     spec:
  #       type: LoadBalancer
  count: 1
  elasticsearchRef:
    name: quickstart
  enterpriseSearchRef:
    name: enterprise-search-quickstart
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.8.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.roles: ["master"]
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms2g -Xmx2g
              resources:
                requests:
                  memory: 1Gi
                  cpu: 1
                limits:
                  memory: 2Gi
    # - name: datanode
    #   count: 1
    #   config:
    #     node.roles: ["data"]
    #   podTemplate:
    #     spec:
    #       containers:
    #         - name: elasticsearch
    #           env:
    #             - name: ES_JAVA_OPTS
    #               value: -Xms2g -Xmx2g
    #           resources:
    #             requests:
    #               memory: 1Gi
    #               cpu: 1
    #             limits:
    #               memory: 2Gi

  # http:
  #   tls:
  #     selfSignedCertificate:
  #       disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
---
apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-quickstart
spec:
  version: 8.8.2
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    # define the exposed URL at which users will reach Enterprise Search
    ent_search.external_url: https://enterprise-search.meshada.com
    # define the exposed URL at which users will reach Kibana
    kibana.host: https://kibana-staging.meshada.com
    # configure app search document size limit
    app_search.engine.document_size.limit: 100kb
  podTemplate:
    spec:
      containers:
        - name: enterprise-search
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
          env:
            - name: JAVA_OPTS
              value: -Xms3500m -Xmx3500m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  # namespace: default
  annotations:
    # cert-manager.io/issue-temporary-certificate: "true"
    # acme.cert-manager.io/http01-edit-in-place: "true"
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: kibana-staging.meshada.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601
    - host: enterprise-search.meshada.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enterprise-search-quickstart-ent-http
                port:
                  number: 3002
  tls:
    - hosts:
        - kibana-staging.meshada.com
        - enterprise-search.meshada.com
      secretName: eck-secret-ingress-prod
