apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.7.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: dea66ec9-3b25-4048-bb4b-e3340ffd6b3a.k8s.civo.com
      http:
        paths:
          - path: /elastic
            pathType: Prefix
            backend:
              service:
                name: quickstart-es-http
                port:
                  number: 9200
