apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.8.0
  # http:
  #   service:
  #     spec:
  #       type: LoadBalancer
  count: 1
  elasticsearchRef:
    name: quickstart
