apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.7.1
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: default
spec:
  rules:
    - host: kibana-ingress.dea66ec9-3b25-4048-bb4b-e3340ffd6b3a.k8s.civo.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601
