apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: gsabbih5@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: traefik
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: meshada-cert
#   namespace: default
# spec:
#   secretName: meshada-secret
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: meshada-cert.d65b47f8-d292-497f-be72-25383e521cac.lb.civo.com
#   dnsNames:
#     - meshada-cert.d65b47f8-d292-497f-be72-25383e521cac.lb.civo.com
