# kubectl create secret docker-registry dockercred \
#     --docker-server=https://docker-staging.meshada.com/repository/nexus-docker/ \
#     --docker-username=gsabbih \
#     --docker-password=kuhrox-3nawfi-gojpAk\
#     --docker-email=gsabbih5@gmail.com

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
