apiVersion: v1
kind: Pod
metadata:
  name: mesdadaapi
spec:
  containers:
    - name: mesdadaapi
      image: image.meshada.com/meshadaapi:prod
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: dockercred
---
apiVersion: v1
kind: Service
metadata:
  name: mesdadaapi-service
spec:
  selector:
    app: mesdadaapi
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8080
