apiVersion: v1
kind: Pod
metadata:
  name: meshadasparkml
spec:
  containers:
    - name: meshadasparkml
      image: image.meshada.com/meshadasparkml:prod
      ports:
        - containerPort: 8090
  imagePullSecrets:
    - name: dockercred
---
apiVersion: v1
kind: Service
metadata:
  name: meshadasparkml-service
spec:
  selector:
    app: meshadasparkml
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
