apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesdadaapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mesdadaapi
  template:
    metadata:
      labels:
        app: mesdadaapi
    spec:
      containers:
        - name: mesdadaapi
          image: image.meshada.com/meshadaapi:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockercred

---
apiVersion: v1
kind: Service
metadata:
  name: mesdadaapi-service
spec:
  selector:
    app: mesdadaapi
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8080
