apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshadasparkml-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meshadasparkml
  template:
    metadata:
      labels:
        app: meshadasparkml
    spec:
      containers:
        - name: meshadasparkml
          image: image.meshada.com/meshadasparkml:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
      imagePullSecrets:
        - name: dockercred

---
apiVersion: v1
kind: Service
metadata:
  name: meshadasparkml-service
spec:
  selector:
    app: meshadasparkml
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
